version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend/api:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/pawswipe
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scraper/backup:/docker-entrypoint-backup.d
    ports:
      - "5433:5432"

volumes:
  db-data:
